# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-29 03:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cpuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ioInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='memoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueUsed', models.FloatField()),
                ('memPercent', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='opStartEnddate',
            fields=[
                ('opCodeID', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(blank=True, max_length=11)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forceX', models.FloatField()),
                ('forceY', models.FloatField()),
                ('forceZ', models.FloatField()),
                ('shakeX', models.FloatField()),
                ('shakeY', models.FloatField()),
                ('shakeZ', models.FloatField()),
                ('acouEmission', models.FloatField()),
                ('time', models.DateTimeField()),
                ('opCodeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bearing.opStartEnddate')),
            ],
        ),
        migrations.CreateModel(
            name='sensorInfo',
            fields=[
                ('sensorID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('addDate', models.DateField()),
                ('machineID', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='opstartenddate',
            name='sensorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bearing.sensorInfo'),
        ),
    ]
