# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locationOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch1', models.FloatField()),
                ('ch2', models.FloatField()),
                ('ch3', models.FloatField()),
                ('ch4', models.FloatField()),
                ('ch5', models.FloatField()),
                ('ch6', models.FloatField()),
                ('ch7', models.FloatField()),
                ('ch8', models.FloatField()),
            ],
        ),
    ]
