# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bearing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='areaCode',
            field=models.CharField(max_length=6, verbose_name='区域代码'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='factorDes',
            field=models.CharField(max_length=100, verbose_name='部门描述'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='factorID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='部门编码'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='location',
            field=models.CharField(max_length=200, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='otherInfo',
            field=models.TextField(blank=True, null=True, verbose_name='备注 '),
        ),
        migrations.AlterField(
            model_name='factory',
            name='personInCharge',
            field=models.CharField(max_length=12, verbose_name='责任人'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machineID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdepart',
            name='departID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensorinfo',
            name='sensorID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
