# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-02 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bearing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forceX', models.FloatField()),
                ('forceY', models.FloatField()),
                ('forceZ', models.FloatField()),
                ('shakeX', models.FloatField()),
                ('shakeY', models.FloatField()),
                ('shakeZ', models.FloatField()),
                ('acouEmission', models.FloatField()),
                ('time', models.DateTimeField()),
                ('opCodeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bearing.opStartEnddate')),
            ],
        ),
        migrations.CreateModel(
            name='WaveletData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forceX', models.FloatField()),
                ('forceY', models.FloatField()),
                ('forceZ', models.FloatField()),
                ('shakeX', models.FloatField()),
                ('shakeY', models.FloatField()),
                ('shakeZ', models.FloatField()),
                ('acouEmission', models.FloatField()),
                ('time', models.DateTimeField()),
                ('opCodeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bearing.opStartEnddate')),
            ],
        ),
    ]
