# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bearing', '0002_auto_20180409_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factory',
            options={'verbose_name': '制造加工厂', 'verbose_name_plural': '制造加工厂'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': '机床', 'verbose_name_plural': '机床'},
        ),
        migrations.AlterModelOptions(
            name='opstartenddate',
            options={'verbose_name': '操作代号/时间', 'verbose_name_plural': '操作代号/时间'},
        ),
        migrations.AlterModelOptions(
            name='productdepart',
            options={'verbose_name': '生产部门', 'verbose_name_plural': '生产部门'},
        ),
        migrations.AlterModelOptions(
            name='sensorinfo',
            options={'verbose_name': '传感器信息', 'verbose_name_plural': '传感器信息'},
        ),
        migrations.AlterModelOptions(
            name='sensorrawdata',
            options={'verbose_name': '传感器源数据', 'verbose_name_plural': '传感器源数据'},
        ),
        migrations.AlterModelOptions(
            name='sensorwaveletdata',
            options={'verbose_name': '小波去噪后数据', 'verbose_name_plural': '小波去噪后数据'},
        ),
        migrations.RemoveField(
            model_name='sensorinfo',
            name='description',
        ),
        migrations.AddField(
            model_name='sensorinfo',
            name='dsensorDes',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='传感器描述'),
        ),
        migrations.AddField(
            model_name='sensorinfo',
            name='sensorCode',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='传感器编码'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machineDes',
            field=models.CharField(max_length=100, verbose_name='机床描述'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machineID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='机床编码'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='otherInfo',
            field=models.TextField(blank=True, null=True, verbose_name='备注 '),
        ),
        migrations.AlterField(
            model_name='sensorrawdata',
            name='sesorValue',
            field=models.FloatField(verbose_name='数值'),
        ),
        migrations.AlterField(
            model_name='sensorwaveletdata',
            name='sesorValue',
            field=models.FloatField(verbose_name='数值'),
        ),
    ]
