# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-13 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bearing', '0003_auto_20180311_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinfo',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
