# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bearing', '0004_auto_20180411_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorrawdata',
            options={'ordering': ['saveDate'], 'verbose_name': '传感器源数据', 'verbose_name_plural': '传感器源数据'},
        ),
        migrations.AlterModelOptions(
            name='sensorwaveletdata',
            options={'ordering': ['saveDate'], 'verbose_name': '小波去噪后数据', 'verbose_name_plural': '小波去噪后数据'},
        ),
    ]
