# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-18 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bearing', '0005_cpuinfo_ioinfo_memoryinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='opStartEnddate',
            fields=[
                ('opCodeID', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='sensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forceX', models.FloatField()),
                ('forceY', models.FloatField()),
                ('forceZ', models.FloatField()),
                ('shakeX', models.FloatField()),
                ('shakeY', models.FloatField()),
                ('shakeZ', models.FloatField()),
                ('acouEmission', models.FloatField()),
                ('time', models.DateTimeField()),
                ('opCodeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bearing.opStartEnddate')),
            ],
        ),
        migrations.CreateModel(
            name='sensorInfo',
            fields=[
                ('sensorID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('addDate', models.DateField()),
                ('machineID', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='locationOne',
        ),
        migrations.AddField(
            model_name='opstartenddate',
            name='sensorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bearing.sensorInfo'),
        ),
    ]
