# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bearing', '0005_auto_20180411_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='opStartEnddate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bearing.opStartEnddate'),
        ),
    ]
