# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bearing', '0006_machine_opstartenddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='opStartEnddate',
        ),
    ]
