# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bearing', '0007_remove_machine_opstartenddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='machineRunTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bearing.machine')),
                ('opStartEnddate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bearing.opStartEnddate')),
            ],
            options={
                'verbose_name': '铣床运行时间段',
                'verbose_name_plural': '铣床运行时间段',
            },
        ),
    ]
