# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-21 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bearing', '0008_machineruntime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemHumConData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TemValue', models.FloatField(verbose_name='温度传感器数据')),
                ('HumValue', models.FloatField(verbose_name='湿度传感器数据')),
                ('ConValue', models.FloatField(verbose_name='可燃气体浓度')),
                ('saveDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
            ],
        ),
        migrations.RemoveField(
            model_name='cpuinfo',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='ioinfo',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='memoryinfo',
            name='machine',
        ),
    ]
