# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bearing', '0012_auto_20180507_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='SensorType',
            field=models.CharField(choices=[(0, '数值型传感器'), (1, '开关型传感器'), (2, '泛型传感器'), (-1, '请选择类型')], default=-1, max_length=2),
        ),
    ]
